name: unit tests
discover: pnpm exec vitest list --filesOnly
run: pnpm exec vitest run --reporter=junit --outputFile="<< outputs.junit >>" --bail 0 << test.atoms >>
analysis: |
  CIRCLECI_COVERAGE=<< outputs.circleci-coverage >> pnpm exec vitest run \
    --config vitest.smarter.config.ts \
    --bail 0 \
    << test.atoms >>
outputs:
  junit: test-reports/tests.xml
  circleci-coverage: coverage.json
options:
  test-impact-analysis: true
  full-test-run-paths:
    - package.json
    - pnpm-lock.yaml
    - vitest.config.ts
    - vitest.smarter.config.ts
    - test/helpers/**
    - .circleci/*.yml
